services:
  Typo3Contentblocks\ContentblocksRegApi\EventListener\AssetRenderer\EnableCbNamespace:
    tags:
      - name: event.listener
        event: TYPO3\CMS\Core\Page\Event\BeforeJavaScriptsRenderingEvent
      - name: event.listener
        event: TYPO3\CMS\Core\Page\Event\BeforeStylesheetsRenderingEvent
  Typo3Contentblocks\ContentblocksRegApi\Backend\Preview\PreviewRenderer:
    autowire: true
    autoconfigure: false
    public: true
  Typo3Contentblocks\ContentblocksRegApi\DataProcessing\CbProcessor:
    autowire: true
    autoconfigure: false
    public: true
  Typo3Contentblocks\ContentblocksRegApi\DataProcessing\FlexFormProcessor:
    autowire: true
    autoconfigure: false
    public: true
  Typo3Contentblocks\ContentblocksRegApi\Generator\FlexFormGenerator:
    autowire: true
    autoconfigure: false
    public: true
  Typo3Contentblocks\ContentblocksRegApi\Generator\TcaGenerator:
    autowire: true
    autoconfigure: false
    public: true
  Typo3Contentblocks\ContentblocksRegApi\Service\ConfigurationService:
    autowire: true
    autoconfigure: false
    public: true
  Typo3Contentblocks\ContentblocksRegApi\Service\DataService:
    autowire: true
    autoconfigure: false
    public: true
  Typo3Contentblocks\ContentblocksRegApi\Service\DatabaseService:
    autowire: true
    autoconfigure: false
    public: true
  Typo3Contentblocks\ContentblocksRegApi\Service\TcaFieldService:
    autowire: true
    autoconfigure: false
    public: true
  Typo3Contentblocks\ContentblocksRegApi\Service\YamlToSqlTranslationService:
    autowire: true
    autoconfigure: false
    public: true
  Typo3Contentblocks\ContentblocksRegApi\Validator\ContentBlockValidator:
    autowire: true
    autoconfigure: false
    public: true
  Typo3Contentblocks\ContentblocksRegApi\Generator\SqlGenerator:
    autowire: true
    autoconfigure: false
    public: true
    tags:
      - name: event.listener
        identifier: 'cb-sql-generator'
        event: TYPO3\CMS\Core\Database\Event\AlterTableDefinitionStatementsEvent
        method: addDatabaseTablesDefinition
