name: CGL & unit tests

on: [push, pull_request]

jobs:
  cgl-and-unit-tests:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.2', '7.3', '7.4', '8.0']
        include:
          - operating-system: 'ubuntu-latest'
            php-versions: '7.2'
    steps:
      -   uses: actions/checkout@v2
      -   uses: shivammathur/setup-php@v2
      -   run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php-version }}
      -   run: composer update --no-interaction --no-progress
      -   run: composer show
      -   run: composer tests-for:ci
