name: CGL & unit tests

on: [push, pull_request]

jobs:
  cgl-and-unit-tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php-version: [7.2, 7.3, 7.4, 8.0]
    steps:
      -   uses: actions/checkout@v2
      # PHP 7.1-.4 are available in ubuntu-18.04
      # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#ubuntu-1804-lts
      -   run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php-version }}
      -   run: composer update --no-interaction --no-progress
      -   run: composer show
      -   run: composer tests-for:ci
