name: docs

on: [push, pull_request]

jobs:
  use-docker-container:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # online, offline
        mode: ['online']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare jobfile
        run: |
          mkdir -p Documentation-GENERATED-temp
          if [[ "${{ matrix.mode }}" = "offline" ]]; then
            echo '{"Overrides_cfg":{"html_theme_options":{"docstypo3org":""}}}' > Documentation-GENERATED-temp/jobfile.json
          fi
          if [[ "${{ matrix.mode }}" = "online" ]]; then
            echo '{"Overrides_cfg":{"html_theme_options":{"docstypo3org":"nonempty"}}}' > Documentation-GENERATED-temp/jobfile.json
          fi
      - name: docker run
        run: |
          docker run --rm --user=$(id -u):$(id -g) \
            -v $(pwd):/PROJECT:ro \
            -v $(pwd)/Documentation-GENERATED-temp:/RESULT \
            t3docs/render-documentation makehtml \
              -c make_singlehtml 1 \
              -c jobfile /RESULT/jobfile.json
      - name: Verify rendering result
        run: stat Documentation-GENERATED-temp/Result/project/0.0.0/index.html || stat Documentation-GENERATED-temp/Result/project/0.0.0/Index.html
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Rendering of ${{ github.event.repository.name }} (mode ${{ matrix.mode }})
          path: ./Documentation-GENERATED-temp/Result/project/0.0.0
